name: Build with Nuitka

on:
  push:
    tags:
      - "v2.*"  # Runs only when a new version tag is pushed

jobs:
  build:
    name: Build Executable
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Adjust if needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: App.py
          mode: standalone
          enable-plugins: tk-inter

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Nuitka-Build-${{ runner.os }}
          path: dist/
