name: Build and Release

on:
  push:
    tags:
      - "v*"  # Triggers when a tag starting with 'v' is pushed

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build binary
        run: |
          pyinstaller --onefile --name GamescoreTracker App.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GamescoreTracker-${{ runner.os }}
          path: dist/GamescoreTracker*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create a release

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
         path: my-artifact
         pattern: my-artifact-*

      - name: Display downloaded files
        run: ls -R my-artifact

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for version ${{ github.ref_name }}.
          files: my-artifact/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
