name: Build and Release Python App

on:
  push:
    tags:
      - "v*"  # Run only on version tags like v1.0

jobs:
  build:
    name: Build Python App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]  # Multi-platform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Briefcase
        run: pip install briefcase

      - name: Build macOS App (if macOS)
        if: runner.os == 'macOS'
        run: |
          briefcase create macOS
          briefcase build macOS
          briefcase package macOS
          mv macOS/build/*/*.app GamescoreTracker-mac.app  # Rename

      - name: Build Windows App (if Windows)
        if: runner.os == 'Windows'
        run: |
          briefcase create windows
          briefcase build windows
          briefcase package windows
          mv windows/build/*/*.exe GamescoreTracker.exe  # Rename

      - name: Build Linux App (if Linux)
        if: runner.os == 'Linux'
        run: |
          briefcase create linux
          briefcase build linux
          briefcase package linux
          mv linux/build/*/*.AppImage GamescoreTracker-linux.AppImage  # Rename

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GamescoreTracker-${{ runner.os }}
          path: |
            GamescoreTracker-mac.app
            GamescoreTracker.exe
            GamescoreTracker-linux.AppImage

  release:
    name: Create GitHub Release
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Built Artifacts
        uses: actions/download-artifact@v4

      - name: Make macOS Binary Executable Again (Just in Case)
        run: chmod +x GamescoreTracker-mac.app || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for version ${{ github.ref_name }}"
          files: |
            GamescoreTracker-mac.app
            GamescoreTracker.exe
            GamescoreTracker-linux.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
