name: Build and Release macOS

on:
  push:
    tags:
      - "v*"  # Runs only when a tag like v1.0 is pushed

jobs:
  build_mac:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build macOS Binary
        run: |
          pyinstaller --onefile --name GamescoreTracker --target-arch universal2 App.py
          chmod +x dist/GamescoreTracker  # Ensure it's executable after building

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GamescoreTracker-mac
          path: dist/GamescoreTracker

  release:
    name: Create GitHub Release
    needs: [build_mac]  # Wait for macOS build to complete
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download the macOS build artifact
        uses: actions/download-artifact@v4
        with:
          name: GamescoreTracker-mac

      - name: Move macOS artifact to a folder
        run: mv GamescoreTracker-mac dist/

      - name: Make macOS Binary Executable Again (Just in Case)
        run: chmod +x dist/GamescoreTracker

      - name: Debug/ Show downloaded macOS artifact
        run: ls -l dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for version ${{ github.ref_name }}.
          files: |
            dist/GamescoreTracker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
