name: Build and Release Python App (macOS)

on:
  push:
    tags:
      - "v*"  # Runs only on version tags like v1.0

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Briefcase
        run: pip install briefcase

      - name: Check for pyproject.toml
        run: |
          if [ ! -f "pyproject.toml" ]; then
            echo "Initializing Briefcase..."
            briefcase new --template standard
          else
            echo "pyproject.toml found, proceeding..."
          fi

      - name: Build macOS App
        run: |
          briefcase create macOS
          briefcase build macOS
          briefcase package macOS
          mv macOS/build/*/*.app GamescoreTracker-mac.app  # Rename

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GamescoreTracker-mac
          path: GamescoreTracker-mac.app

  release:
    needs: [build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Built macOS Artifact
        uses: actions/download-artifact@v4

      - name: Make macOS Binary Executable
        run: chmod +x GamescoreTracker-mac.app || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for version ${{ github.ref_name }}"
          files: GamescoreTracker-mac.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
